### ISSUE TITLE
Could not resolve './BrowserRouter'

### ISSUE THREAD

**Issue by sayhicoelho** [qutran/swheel#10]
Maybe missing .svelte extension for files? I don't understand why can't run the lib.

My code:
```js
import { Router, Route } from 'swheel'
``` 

The error: 
![image](https://user-images.githubusercontent.com/8188365/64215506-834abc80-ce8b-11e9-8235-99b46b394193.png)

Thank you for sharing this awesome lib! I'm looking for some router lib for Svelte and this is the most powerful I've seem.

**Comment by qutran** [comment]
Thanks for feedback! Yes, it's definitely an issue. Currently it's implies to use rollup-plugin-extension (it's unnecessary in the webpack by default) in your bundle configuration to resolve pathes without /index.* and extensions. But I see that it should be compiled to use without it. Will fix it soon

**Comment by qutran** [comment]
@sayhicoelho Fix delivered in the 1.1.3 version. Feel free to reopen in the case if it doesn't help you
