### ISSUE TITLE
transition out bug

### ISSUE THREAD

**Issue by timeshift92** [qutran/swheel#7]
![image](https://user-images.githubusercontent.com/13614530/61373871-672b9580-a8b4-11e9-965f-4112918021c5.png)

happens when switching from tab to tab, reduce 3.6.7

**Comment by qutran** [comment]
Sorry for a long time response. Fix delivered.
Related to https://github.com/sveltejs/svelte/issues/3165
If you are using webpack for bundling please remove `exclude: /node_modules/` from the svelte's loader rule and add `mainFields: ['svelte', 'browser', 'module', 'main']` to the `resolve` field
